name: Build and Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET SDK 3.1
      # Fix for https://github.com/actions/setup-dotnet/issues/29#issuecomment-548740241
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET SDK 5.0.x
      # Fix for https://github.com/actions/setup-dotnet/issues/29#issuecomment-548740241
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build on Windows
      if: matrix.os == 'windows-latest'
      run: .\build.cmd

    - name: Build on Unix
      if: matrix.os != 'windows-latest'
      run: ./build.sh
